language: node_js 

node_js: stable 

cache:
    apt: true
    directories:
        - node_modules 

before_install:
    - npm install hexo-cli -g

install:
    - npm install # 安装hexo及插件

before_script:
    - mv -f replace/inline.js node_modules/kramed/lib/rules/inline.js
    
script:
    - hexo clean # 清除
    - hexo g # 生成
    #- hexo d

after_script:
    - git init pub_web
    - cd pub_web # 进入到git仓库
    - git remote add origin ${GH_REF}
    - cp -rf ../public/* . 
    - git config --global cuser.name "${USER_NAME}"
    - git config --global user.email "${USER_EMAIL}"
    - git add .
    - git commit -am "Automatic Construction :$(date '+%Y-%m-%d %H:%M:%S' -d '+8 hour')" # 零时区，+8小时
    - git push origin master -f
branches:
    only:
        - source #只监测master分支,这是我自己的博客，所以就用的master分支了。
env:
    global:
        - GH_REF: "https://${USER_NAME}:${GITHUB_TOKEN}@github.com/${USER_NAME}/Blog.git" 
        #设置GH_REF，注意更改yourname,GITHUB_TOKEN:就是我们在travis-ci仓库中配置的环境变量
